spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://51.250.26.59:5432/pc_db
    username: secUREusER
    password: StrongEnoughPassword)
    driver-class-name: org.postgresql.Driver
