server:
  port: 8080

spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/v1/auth/**
#          filters:
#            - ApiAuthFilter
#
#        - id: account-service
#          uri: lb://account-service
#          predicates:
#            - Path=/api/v1/info/**
#          filters:
#            - ApiAuthFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret:
    access: 9ebef73f51e99ddc77a58f72be6f123a52faff38f47149ce91a061e0600b2f15
    refresh: 3a1f1cfffa888cc706918a1a19b9310c41dcbd36cdcdd89ee6bc11e2c5eb3ace